server:
  name: Tiktok
  port: 8088
  readTimeout: "60s"
  writeTimeout: "60s"

database:
  host:     127.0.0.1
  port:     9887
  name:     Tiktok
  user:     root
  password: lht12138
  maxOpen:  200
  maxConn:  200

jaeger:
  host: 127.0.0.1
  port: 39411
  path: traces

minio:
  host: 127.0.0.1
  port: 9000
  accessKeyID: admin
  secretAccessKey: 1766551219.qwe.

auth:
  md5Salt: PJzxlk8RcBwwDAtVupPf
  jwtSecret: f89BLFB8Pdt7a9Q