server:
  name: Tiktok
  port: 8088

database:
  host:     127.0.0.1
  port:     9887
  name:     Tiktok
  user:     root
  password: lht12138
  maxOpen:  200
  maxConn:  200

jaeger:
  host: 127.0.0.1
  port: 12137
  path: trace


auth:
  md5Salt: PJzxlk8RcBwwDAtVupPf
  jwtSecret: