{
 "title": "Application-GinExporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total API ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (RequestCount{job=\"$job\", instance=\"$instance\", code=\"200\"}) by (path)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestCount{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Druration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(RequestDuration{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestErrorCount{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestCount {instance=\"$instance\", method=\"GET\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total POST",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestCount {instance=\"$instance\", method=\"POST\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DELETE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestCount {instance=\"$instance\", method=\"DELETE\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(RequestCount {instance=\"$instance\", method=\"PUT\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(5, sum(RequestCount{instance=\"$instance\"}) by (path)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum (delta(RequestCount{instance=\"$instance\"}[2m])) by(path) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(RequestCount{instance=\"$instance\"})by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Error Sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(RequestErrorCount{instance=\"$instance\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (delta(RequestDuration{instance=\"$instance\"}[3m])) by(path) / 1.5",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RequestDetail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(RequestCount{instance=\"$instance\"}) by(path, method, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum (delta(RequestCount{instance=\"$instance\"}[2m])) by(path, code, method) / 2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}