global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: application
    static_configs:
      - targets: ['localhost:8088']
        labels:
          instance: Tiktok-Gin

# docker run -p 39090:9090 -v /root/project/tiktok/config/prometheus.yaml:/etc/prometheus/prometheus.yaml prom/prometheus